server:
  port: 8081

spring:
  application:
    name: pdd-refund
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
          temperature: 0.5
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: rag-test
